go get github.com/GoIncremental/negroni-sessions/cookiestore
go get github.com/goincremental/negroni-sessions
go get github.com/gorilla/mux
go get github.com/lib/pq
go get github.com/mattn/go-sqlite3
go get github.com/urfave/negroni
go get github.com/yosssi/ace
go get golang.org/x/crypto/bcrypt
go get gopkg.in/gorp.v1
go get github.com/tools/godep